### ISSUE TITLE
The button display is abnormal

### ISSUE THREAD

**Issue by w065** [rounk-ctrl/win32-darkmode#1]
When I try to change the button theme to black, there is an additional white border around it. Just like this:
![image](https://github.com/rounk-ctrl/win32-darkmode/assets/105098765/9286de29-76b2-4dbc-9226-1921c72fcf66)
I have written the code as follows:
SetWindowTheme([handle to the control], L"Explorer", NULL);
AllowDarkModeForWindow([handle to the control], true);
SendMessageW([handle to the control], WM_THEMECHANGED, 0, 0);
The picture in the readme looks good, and I really want to know how it was made:
![image](https://github.com/rounk-ctrl/win32-darkmode/assets/105098765/2deb8336-d0b5-48bd-8cc1-d9d12f71b6f1)
Furthermore, I have successfully implemented a dark mode effect using radio buttons and checkboxes. However, the source code does not provide a dark mode interface for regular buttons. Looking forward to your response. Thank you very much!

**Comment by rounk-ctrl** [comment]
you have to do this in your WndProc
```cpp
 if (uMsg == WM_CTLCOLORBTN) {
        if (IsDarkMode)
        {
            HDC hdc = reinterpret_cast<HDC>(wParam);
            SetBkColor(hdc, RGB(25,25,25));
            SetTextColor(hdc, RGB(255,255,255);
        }
        return reinterpret_cast<INT_PTR>(CreateSolidBrush(RGB(25,25,25)));
    }
```

**Comment by w065** [comment]
It's working! Thank you very much for your help! To be honest, this project is the most complete Win32 dark theme I have ever seen, bar none. It includes almost all commonly used controls! I really want to understand how it works. I have encountered some other issues during use, such as the background color of the combo box being white. I hope the complete project can be open-sourced. Thank you very, very much!

Below is my combo box: 
![image](https://github.com/rounk-ctrl/win32-darkmode/assets/105098765/f6404973-32c1-4201-8b57-7e7dde6b7451)
![image](https://github.com/rounk-ctrl/win32-darkmode/assets/105098765/a68ffb22-e8e1-4f92-8d2b-10fdb9617fe0)

**Comment by rounk-ctrl** [comment]
```cpp
if (message == WM_CTLCOLOREDIT || message == WM_CTLCOLORLISTBOX) {
        if (IsDarkMode)
        {
            HDC hdc = reinterpret_cast<HDC>(wParam);
            SetBkColor(hdc, RGB(56,56,56));
            SetTextColor(hdc, RGB(255,255,255));
        }
        return reinterpret_cast<INT_PTR>(CreateSolidBrush(RGB(56,56,56)));
    }
```

**Comment by rounk-ctrl** [comment]
ill upload that sample app ig

**Comment by w065** [comment]
That's fantastic!
